---
title: 'rcrisp: An R package for urban river space delineation'
tags:
  - urban rivers
  - urban morphology
  - delineation
authors:
  - name: Claudiu Forgaci
    orcid: 0000-0003-3218-5102
    equal-contrib: true
    corresponding: true
    affiliation: 1
  - name: Francesco Nattino
    orcid: 0000-0003-3286-0139
    equal-contrib: true
    affiliation: 2
affiliations:
 - index: 1
   name: Delft University of Technology, Julianalaan 134, 2628 BL Delft, The Netherlands
 - index: 2
   name: Netherlands eScience Center, Science Park 140, 1098 XG Amsterdam, The Netherlands
date: 13 August 2017
bibliography: paper.bib
output:
  md_document:
    variant: markdown
# preserve-yaml: true
# filters: ["yaml-filter.lua"]
---

# Summary

`rcrisp` is a software for automated and scalable delineation of urban
river spaces with spatial-temporal big data. 

# Introduction

Urban rivers and the urban areas surrounding them, hereinafter referred
to as urban river spaces (URS), have come to the forefront of
sustainable urban transformations worldwide. This trend is not only due
to pounding water-related disturbances such as floods or water scarcity,
but also because the vital role of rivers in supporting social and
ecological processes is increasingly acknowledged. As researchers and
practitioners of the
urban environment engage into understanding or tackling current URS transformations,
they face the challenge of capturing the complexities of environmental,
social, and ecological phenomena in an integrated way [@prominski2023].
Moreover, considering the global extent of the phenomenon, they lack
established frames of comparison that may reveal local specificities and
cross-case similarities. An essential part of the challenge is how urban
areas surrounding rivers are delineated---that is, how their boundaries
are drawn for analytical or intervention purposes---, as the resulting
spatial units can considerably impact decisions made for urban
riverspace transformations. More often than not, URS boundaries are
determined without a systematic and reproducible delineation method,
wherever suitable spatial data is available, based on census tracts,
using rivers as boundaries, using neutral (square or circular) cut-outs,
at different levels of aggregation (city, district, neighbourhood), or
areas of study specific to a local urban development project. None of
these approaches to delineation are suitable for a reliable integrated
understanding of URSs, as they are to a large extent arbitrary. An
integrated understanding of URS requires spatial morphological units of
analysis that reflect the combined “footprints” of environmental, social
and ecological processes [@marcus2016]. This is a case of the modifiable
areal unit problem (MAUP) [@openshaw1984] with a considerable impact on
decisions taken in environmental, mobility, ecological, and public space
planning and design.

# Statement of need

`rcrisp` is designed to address a diverse, growing and cross-disciplinary 
research community concerned with understanding URSs in an integrated and
scalable way. 

`rcrisp` provides specialized
functionality in addition to more general morphometric tools like the
Python packages `momepy` [@fleischmann2019; @fleischmann2022 and `OSMnx`
[@boeing2024] and the R package `sfnetworks` [@vandermeer2024].

`rcrisp` is intended to open new research avenues, such as integrated local
spatial analyses and global cross-case analyses, which have been so far
hindered by data- or workflow-related difficulties. However, the
usability and effectiveness of `rcrisp` in addressing the needs, challenges
and various use cases of researchers and practitioners is yet to be
tested and the software needs to be adapted according to such input.

# Algorithms

`rcrisp` builds on a previously developed delineation method [@Forgaci2018], 
which considers the morphology of the river valley and that of the urban fabric
jointly. `rcrisp` automates that method of delineation, while leveraging local
and global spatial-temporal big data (e.g., OpenStreetMap and Global DEM data) increasingly available for riverspace analysis at large [@forgaci2020]. The
automation of the delineation is implemented using the following algorithms:

- A cost distance algorithm is used to determine the river valley boundaries 
from a DEM.

- A shortest path algorithm is used to determine the corridor edges on the
street network obtained from OpenStreetMap. The valley boundaries are used to 
adjust the corridor edges to the 

- The COINS algorithm is used to determine continuous lines along the street
network starting from bridges crossing the river. The resulting continuous lines
are used to divide the corridor into corridor segments.

- An isovist algorithm is used to determine the space enclosed by the first line
of buildings around the river within a given visibility distance.

# Related software

# Software package overview

Modules...

-   corridor

-   delineate

-   network

-   osmdata

-   utils

-   valley

# Acknowledgements

# Author contributions

# References
